name: 'pr-review'
on: [pull_request]
jobs:
  job1:
    name: 'code-review'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: first
        uses: RajaniBansal/ai-review@main
        with:
          openai-key: ${{ secrets.OPENAI_API_KEY }}
